config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index, :create]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 validates :name, presence: true, uniqueness: true,
                  length: { minimum:2 , maximum:20 }
 
 validates :introduction, length: { maximum: 50 }
 
 has_many :books, dependent: :destroy
 has_many :users, dependent: :destroy
 
 attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @book = Book.new
  end

  def index
   @users = User.all
   @new_book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profile was successfully updated."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
    
    def correct_user
        @user = User.find(params[:id])
     unless @user == current_user
       redirect_to user_path(current_user)
     end
    end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>

<div class="col-xs-3">
  <h2> User info </h2>
  <%= attachment_image_tag user, :profile_image, size: '100x100', fallback: 'no_image.jpg' %>
  <table class="table">
    <tbody>
      <tr>
        <th> name </th>
        <th> <%= user.name %> </th>
      </tr>
      <tr>
        <th> introduction </th>
        <th> <%= user.introduction %> </th>
      </tr>
    </tbody>
  </table>
  <div class="row">
        <% if user == current_user %>
        <%= link_to '', edit_user_path(current_user), method: :get, class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        <% else %>
        <%= link_to '', edit_user_path(user), method: :get, class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        <% end %>
   </div>


  <h2> New book</h2>
  
  <%= form_with model: book, local:true do |f| %>
    <div class="field row">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, :class => 'form-control book_title' %>
    </div>

    <div class="field row">
      <%= f.label :body, 'Opinion' %>
      <%= f.text_area :body, :class => 'form-control book_title' %>
    </div>

    <br>

    <div class="actions row">
      <%= f.submit "Create Book", :class => 'btn btn-success ' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>
  
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>User info</h1>
  		
　　　<%= form_with model: @user, local:true do |f| %>
      <div class="field row">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, :class => 'form-control user_name' %>
      </div>
      
     
      <div class="field row">
       <label>Image</label>
       <%= f.attachment_field :profile_image %>
      </div>
    
      <div class="field row">
       <%= f.label :introduction, 'Introduction' %>
       <%= f.text_area :introduction, :class => 'form-control user_introduction' %>
      </div>
    
    <br>
    
    <div class="actions row">
      <%= f.submit "Update User", :class => 'btn btn-success ' %>
    </div>
  <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
             <%# UserInfo NewBook %>
             <%= render 'users/list', user: current_user, book: @new_book %>
            </div>
        </div>
        
        <div class="col-md-8 offset-md-1">
        <h2> Users </h2>
         <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th> image </th>
            <th> name </th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <% @users.each do |user| %>
        <tr>
           <td>
             <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40' %>
           </td>
           <td><%= user.name %></td>
           <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
         <% end %>
         </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
             <%# UserInfo NewBook %>
             <%= render 'users/list', user: @user, book: @new_book %>
            </div>
        </div>
        
        <div class="col-md-8 offset-md-1">
        <h2> Books </h2>
         <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th> Title </th>
            <th> Opinion </th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <tbody>
           <%# 自分の投稿一覧表示 %>
            <% @books.each do |book_info| %>
            <tr>
             <td>
               <%= link_to attachment_image_tag(book_info.user, :profile_image, size: '40x40', fallback: 'no_image.jpg'), user_path(book_info.user)%>
             </td>
             <td>
               <%= link_to book_info.title, book_path(book_info.id) %> 
             </td>
             <td>
               <%= book_info.body %>
             </td>
             <% end %>
            </tr>
           
          </tbody>
         </table>
    </div>
</div>