config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index, :create]
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
   validates :title, presence: true
   validates :body, presence: true,
                    length: { maximum:200 }
                    
  has_many :books, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    book = @new_book
    if book.save
     flash[:notice] = "Book was successfully created."
    redirect_to book_path(book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.find(current_user.id)
    @books = Book.all
    @new_book = Book.new
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
   @book = Book.find(params[:id])
   if @book.user == current_user
    render "edit"
   else
    redirect_to books_path
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
       redirect_to book_path
    else 
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
  <% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

　　　<%= form_with model: @book, local:true do |f| %>
      <div class="field row">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, :class => 'form-control book_title' %>
      </div>

    <div class="field row">
      <%= f.label :body, 'Opinion' %>
      <%= f.text_area :body, :class => 'form-control book_title' %>
    </div>

    <br>

    <div class="actions row">
      <%= f.submit "Update Book", :class => 'btn btn-success ' %>
    </div>
    <% end %>
    <div>
	   <%= link_to "Show", book_path(@book) %> |
	   <%= link_to "Back", books_path %>
	  </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
             <%# UserInfo NewBook %>
             <%= render 'users/list', user: current_user, book: @new_book %>
            </div>
        </div>
        
        <div class="col-md-8 offset-md-1">
        <h2> Books </h2>
         <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th> Title </th>
            <th> Opinion </th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book_info| %>
            <tr>
             <td>
               <%= link_to attachment_image_tag(book_info.user, :profile_image, size: '40x40', fallback: 'no_image.jpg'), user_path(book_info.user)%>
             </td>
             <td>
               <%= link_to book_info.title, book_path(book_info.id) %> </td>
             <td>
               <%= book_info.body %>
             </td>
            </tr>
           <% end %>
          </tbody>
         </table>
    </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
    <div class="row">
    <%= render 'users/list', user: @user, book: @new_book %>
    </div>
   </div>

  <div class="col-md-8 offset-md-1">
   <h3>Book detail</h3>
    <table class='table table-hover table-inverse'>
　   <tbody>
　　  <tr>
       <td>
        <%= link_to(user_path(@book.user)) do %>
        <% if @book.user == current_user %>
        <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
        <% else %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
        <% end %>
        <div>
        <%= @book.user.name %><% end %>
        </div>
       </td>
       <td><%= link_to(book_path(@book)) do %>
                 <%= @book.title %>
               <% end %>
       </td>
　　　 <td><%= @book.body %>
　　　 </td>
         <% if @book.user == current_user %>
          <%= link_to edit_user_path(current_user.id) do %>
            <td><%= link_to 'Edit', edit_book_path(@book), method: :get, class: "btn btn-success btn-xs text_light" %></td>
          <% end %>
           <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, class: "btn btn-danger btn-xs text_light" %></td>
         <% end %>
　　　 </tr>
　    </tbody>
     </table>

  </div>
 </div>
</div>