config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get "home/about" => "home#about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index, :create]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <%= link_to " HOME ", user_path(current_user.id), method: :get, class: "fas fa-home nav-link text-light" %>
             <%= link_to " Users ", users_path, method: :get, class: "fas fa-users nav-link text-light" %>
             <%= link_to " Books ", books_path, method: :get, class: "fas fa-book-open nav-link text-light" %>
             <%= link_to " logout ", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
            <% else %>
             <%= link_to " HOME ", root_path, method: :get, class: "fas fa-home nav-link text-light" %>
             <%= link_to " About ", home_about_path, method: :get, class: "fas fa-link nav-link text-light" %>
             <%= link_to " sign up ", new_user_registration_path, method: :get, class: "fas fa-user-plus nav-link text-light" %>
             <%= link_to " login ", new_user_session_path, method: :get, class: "fas fa-sign-in-alt nav-link text-light" %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

        <p id="notice"><%= notice %></p>

        <%= yield %>

      </div>
    </div>
  </html>